services:
  pi:
    image: ghcr.io/qmaru/agent/pi
    environment:
      PI_SKIP_VERSION_CHECK: 1
      PI_OFFLINE: 1
    env_file:
      - .env
    volumes:
      - ./examples/models.json:/root/.pi/agent/models.json
      - ./examples/settings.json:/root/.pi/agent/settings.json
      - ./examples/mcp.json:/root/.pi/agent/mcp.json
    entrypoint:
      - pi
